// Builds test/desk-pack/: every source fixture converted to each other desk,
// plus a checklist, for loading on real desks and their editors. Run with
// `npm run desk-pack`; test/desk-pack.test.js fails when the pack is stale.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { DESKS, readScene, writeScene, reportRows } from '../js/conversion.js';
import { makeChannel } from '../js/scene.js';
import { X32_ICON_TO_WING } from '../js/console-map.js';

const FIXTURES = new URL('../test/fixtures/', import.meta.url);
const OUT = new URL('../test/desk-pack/', import.meta.url);

const SOURCES = [
  { id: 'gdq-x32',     desk: 'x32',  file: 'real/gdq/sgdq2023-post.scn',      about: 'real X32 show (GamesDoneQuick SGDQ 2023)' },
  { id: 'gdq-wing',    desk: 'wing', file: 'real/gdq/pre-sgdq2025.snap',      about: 'real WING-EDIT 3.1 snapshot (GamesDoneQuick 2025)' },
  { id: 'meeting-xair', desk: 'xair', file: 'real/hedgcoxekhav/meeting.scn',  about: 'real X Air meeting-room scene (hedgcoxekhav)' },
  { id: 'synthetic-x32', desk: 'x32', file: 'synthetic-x32.scn',              about: 'hand-written X32 scene (linked pair, EQ, DCAs)' },
];

const LOAD_WITH = {
  xair: 'X-AIR-Edit connected to the XR18: File → Load Scene (the desk itself parses it)',
  x32:  'X32-Edit, offline: open the scene file',
  wing: 'WING-EDIT, offline: load the snapshot',
};

// What each X32 icon is drawn as (X32 protocol doc p.139), short enough for a
// channel name. The icon check snapshots name each channel after its X32
// picture and give it the Wing icon the converter maps it to, so opening them
// in WING-EDIT shows every pairing at once.
const X32_ICON_PICTURES = [
  'none', 'kick back', 'kick front', 'snare top', 'snare bottom', 'tom H', 'tom M', 'floor tom',
  'hi-hat', 'ride', 'drum kit', 'cowbell', 'bongos', 'congas', 'tambourine', 'vibraphone',
  'bass', 'bass 2', 'guitar', 'les paul', 'pointy guitar', 'flying V', 'acoustic', 'bass amp',
  'guitar amp', 'cabinet', 'grand piano', 'upright', 'keys on table', 'keys on X', 'synth 1',
  'synth 2', 'synth 3', 'keytar', 'trumpet', 'trombone', 'sax', 'clarinet', 'violin', 'cello',
  'male vox', 'female vox', 'choir', 'hand sign', 'talk A', 'talk B', 'big mic', 'pencil mic',
  'pencil mic 2', 'handheld', 'wireless', 'podium', 'ear', 'XLR', 'jack', 'jack L', 'jack R',
  'RCA L', 'RCA R', 'reel to reel', 'FX', 'laptop', 'twin speaker', 'speaker L', 'speaker R',
  'line array', 'speaker stand', 'rack', 'routing', 'faders', 'bus', 'matrix', 'grid', 'smiley',
];

function iconCheck(first, last) {
  const channels = [];
  for (let x = first; x <= last; x++) {
    const ch = x - first + 1;
    channels.push(makeChannel({ ch, index: ch, name: `${x} ${X32_ICON_PICTURES[x - 1]}`.slice(0, 16), icon: x }));
  }
  const scene = { name: `Icons ${first}-${last}`, channels, dcas: [], buses: [], matrices: [], losses: [] };
  return writeScene(scene, 'wing').file.text;
}

export function buildDeskPack() {
  const files = [];
  const sections = [];

  for (const src of SOURCES) {
    const scene = readScene(src.desk, readFileSync(new URL(src.file, FIXTURES), 'utf8'), src.file);
    for (const to of Object.keys(DESKS).filter(d => d !== src.desk)) {
      const out = writeScene(scene, to);
      const name = `${src.id}-to-${to}.${out.file.ext}`;
      files.push({ path: name, content: out.file.text });

      const named = out.preview.filter(p => p.name);
      const stereo = named.filter(p => p.stereo).map(p => p.name);
      const report = reportRows(out.losses);
      sections.push([
        `### ${name}${to === 'xair' ? '  ← test on the XR18' : ''}`,
        '',
        `From the ${src.about}, written for the ${DESKS[to].label}.`,
        `Load with: ${LOAD_WITH[to]}.`,
        '',
        `- **Loads without an error?**`,
        `- **${named.length} named channels**, in order: ${named.map(p => p.name).join(', ') || '(none)'}`,
        `- **Stereo:** ${stereo.join(', ') || '(none)'}`,
        `- **DCAs written:** ${out.stats.dcas}`,
        '',
        report.length
          ? `The converter's report (${report.length} lines), each worth checking on the desk:\n\n` +
            report.map(r => `- \`${r.severity}\` ${r.text}`).join('\n')
          : 'The converter reported nothing lost.',
        '',
      ].join('\n'));
    }
  }

  files.push({ path: 'icons-1-40.snap', content: iconCheck(1, 40) });
  files.push({ path: 'icons-41-74.snap', content: iconCheck(41, 74) });

  files.push({ path: 'README.md', content: [
    '# Desk test pack',
    '',
    'Converter output to load on real desks and their editors. Generated by `npm run desk-pack`;',
    '`test/desk-pack.test.js` fails if these files no longer match what the converter writes.',
    '',
    '## On every file',
    '',
    '- It loads, with no error or partial load.',
    '- Channel names and colors match the list below.',
    '- The patch: X32 routing blocks, per-channel sources, USB returns on the X Air.',
    '- Stereo pairs are linked, and nothing sits on the wrong side.',
    '- EQ (bands, cuts, shelves), gate and compressor match the source.',
    '- Bus sends, levels and tap points (pre/post/group).',
    '- DCA and mute-group membership.',
    '- Each line of the converter\'s report is true on the desk.',
    '',
    '## Answered in the desks\' editors, offline (#24, 2026-09-25)',
    '',
    '- The Wing uses `#M` mute-group tags, comma-separated from `#D`: `#D3,#M1` (WING-EDIT 3.3.3).',
    '- WING-EDIT 3.3.3 loads `"type": "snapshot.11"`.',
    '- X32-Edit and X-AIR-Edit take plain frequencies (`4675.0`, `3430.0`) and snap them to the desk\'s',
    '  own steps (4k68, 3k43). Gains snap too: -5.30 dB lands on -5.25 on the X32.',
    '',
    'A desk on older firmware may still differ from its editor; load a converted file into a spare',
    'scene slot first.',
    '',
    '## Icons (#42)',
    '',
    '`icons-1-40.snap` and `icons-41-74.snap` need only WING-EDIT, offline. Each channel is named',
    'after an X32 icon (its number and what the X32 draws) and carries the Wing icon the converter',
    'maps it to. The picture on each strip should match its name; note any that do not.',
    '',
    ...Object.entries(X32_ICON_TO_WING).map(([x, w]) => `- X32 ${x} ${X32_ICON_PICTURES[x - 1]} → Wing ${w}`),
    '',
    '## Files',
    '',
    ...sections,
  ].join('\n') });

  return files;
}

// Run directly: write the pack.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  mkdirSync(OUT, { recursive: true });
  const files = buildDeskPack();
  for (const f of files) writeFileSync(new URL(f.path, OUT), f.content);
  console.log(`wrote ${files.length} files to test/desk-pack/`);
}
