// Builds test/desk-pack/: every source fixture converted to each other desk,
// plus a checklist, for loading on real desks and their editors. Run with
// `npm run desk-pack`; test/desk-pack.test.js fails when the pack is stale.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { DESKS, readScene, writeScene, reportRows } from '../js/conversion.js';

const FIXTURES = new URL('../test/fixtures/', import.meta.url);
const OUT = new URL('../test/desk-pack/', import.meta.url);

const SOURCES = [
  { id: 'gdq-x32',     desk: 'x32',  file: 'real/gdq/sgdq2023-post.scn',      about: 'real X32 show (GamesDoneQuick SGDQ 2023)' },
  { id: 'gdq-wing',    desk: 'wing', file: 'real/gdq/pre-sgdq2025.snap',      about: 'real WING-EDIT 3.1 snapshot (GamesDoneQuick 2025)' },
  { id: 'meeting-xair', desk: 'xair', file: 'real/hedgcoxekhav/meeting.scn',  about: 'real X Air meeting-room scene (hedgcoxekhav)' },
  { id: 'synthetic-x32', desk: 'x32', file: 'synthetic-x32.scn',              about: 'hand-written X32 scene (linked pair, EQ, DCAs)' },
];

const LOAD_WITH = {
  xair: 'X-AIR-Edit connected to the XR18: File → Load Scene (the desk itself parses it)',
  x32:  'X32-Edit, offline: open the scene file',
  wing: 'WING-EDIT, offline: load the snapshot',
};

export function buildDeskPack() {
  const files = [];
  const sections = [];

  for (const src of SOURCES) {
    const scene = readScene(src.desk, readFileSync(new URL(src.file, FIXTURES), 'utf8'), src.file);
    for (const to of Object.keys(DESKS).filter(d => d !== src.desk)) {
      const out = writeScene(scene, to);
      const name = `${src.id}-to-${to}.${out.file.ext}`;
      files.push({ path: name, content: out.file.text });

      const named = out.preview.filter(p => p.name);
      const stereo = named.filter(p => p.stereo).map(p => p.name);
      const report = reportRows(out.losses);
      sections.push([
        `### ${name}${to === 'xair' ? '  ← test on the XR18' : ''}`,
        '',
        `From the ${src.about}, written for the ${DESKS[to].label}.`,
        `Load with: ${LOAD_WITH[to]}.`,
        '',
        `- **Loads without an error?**`,
        `- **${named.length} named channels**, in order: ${named.map(p => p.name).join(', ') || '(none)'}`,
        `- **Stereo:** ${stereo.join(', ') || '(none)'}`,
        `- **DCAs written:** ${out.stats.dcas}`,
        '',
        report.length
          ? `The converter's report (${report.length} lines), each worth checking on the desk:\n\n` +
            report.map(r => `- \`${r.severity}\` ${r.text}`).join('\n')
          : 'The converter reported nothing lost.',
        '',
      ].join('\n'));
    }
  }

  files.push({ path: 'README.md', content: [
    '# Desk test pack',
    '',
    'Converter output to load on real desks and their editors. Generated by `npm run desk-pack`;',
    '`test/desk-pack.test.js` fails if these files no longer match what the converter writes.',
    '',
    '## On every file',
    '',
    '- It loads, with no error or partial load.',
    '- Channel names and colours match the list below.',
    '- The patch: X32 routing blocks, per-channel sources, USB returns on the X Air.',
    '- Stereo pairs are linked, and nothing sits on the wrong side.',
    '- EQ (bands, cuts, shelves), gate and compressor match the source.',
    '- Bus sends, levels and tap points (pre/post/group).',
    '- DCA and mute-group membership.',
    '- Each line of the converter\'s report is true on the desk.',
    '',
    '## Open questions only a desk can answer (#24)',
    '',
    '- Does the Wing honour the `#M` mute-group tags we write? Only `#D` (DCA) is documented.',
    '- Does the Wing accept `"type": "snapshot.11"`? WING-EDIT 3.1 writes `snapshot.9`.',
    '- Do the X32 and X Air accept frequencies written as `10020.0` rather than `10k02`?',
    '',
    '## Files',
    '',
    ...sections,
  ].join('\n') });

  return files;
}

// Run directly: write the pack.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  mkdirSync(OUT, { recursive: true });
  const files = buildDeskPack();
  for (const f of files) writeFileSync(new URL(f.path, OUT), f.content);
  console.log(`wrote ${files.length} files to test/desk-pack/`);
}
